type AegisVariations {
  Id: string @unique
  DefendsAgainstPhysical: bool
  DefendsAgainstFire: bool
  DefendsAgainstCold: bool
  DefendsAgainstLightning: bool
  DefendsAgainstChaos: bool
  BuffDefinition: BuffDefinitions
  DepletedBuffDefinition: BuffDefinitions
  PersistValueBuffDefinition: BuffDefinitions
  AlternateEffects: [MiscAnimated]
  _: bool
  _: [string]
}