type CharacterCreationButton {
  Character: Characters
  Texture: string @file(ext: ".dds")
  TextureHovered: string @file(ext: ".dds")
  TextureSelected: string @file(ext: ".dds")
  TextureSelectedHovered: string @file(ext: ".dds")
}