type GeometryAttack {
  _: i32
  Effect: [MiscAnimated]
  HitEffect: [MiscAnimated]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: [_] # All rows empty
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  Debuff: BuffDefinitions
  DebuffStatValues: [i32]
  _: i32
  _: bool
  _: bool
  DebuffVisual: BuffVisuals
  _: bool
  _: [i32]
  _: bool
  _: bool
  GeometryChannel: GeometryChannel
  _: bool
  _: bool
  _: [_] # All rows empty
  _: bool
  _: bool
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  ExecuteGEAL: ExecuteGEAL
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: rid
  _: string
  _: i32
}