type Hideouts {
  HideoutArea: WorldAreas
  HASH16: u16
  HideoutFile: string @file(ext: ".hideout")
  ClaimSideArea: WorldAreas
  HideoutImage: string
  IsEnabled: bool
  _: bool
  Name: string
  _: [i32]
  _: bool
  MtxUnlock: MtxTypes
  _: string
}