type MonsterResistances {
  Id: string @unique
  NormalFireResists: [i32]
  NormalFireBrackets: [i32]
  MagicFireResists: [i32]
  MagicFireBrackets: [i32]
  RareFireResists: [i32]
  RareFireBrackets: [i32]
  UniqueFireResists: [i32]
  UniqueFireBrackets: [i32]
  NormalColdResists: [i32]
  NormalColdBrackets: [i32]
  MagicColdResists: [i32]
  MagicColdBrackets: [i32]
  RareColdResists: [i32]
  RareColdBrackets: [i32]
  UniqueColdResists: [i32]
  UniqueColdBrackets: [i32]
  NormalLightningResists: [i32]
  NormalLightningBrackets: [i32]
  MagicLightningResists: [i32]
  MagicLightningBrackets: [i32]
  RareLightningResists: [i32]
  RareLightningBrackets: [i32]
  UniqueLightningResists: [i32]
  UniqueLightningBrackets: [i32]
  NormalChaosResists: [i32]
  NormalChaosBrackets: [i32]
  MagicChaosResists: [i32]
  MagicChaosBrackets: [i32]
  RareChaosResists: [i32]
  RareChaosBrackets: [i32]
  UniqueChaosResists: [i32]
  UniqueChaosBrackets: [i32]
}