type MtxTypes {
  Id: string
  Hash32: i32 @unique
  Name: string @localized
  _: string @localized
  Description1: string @localized
  Description2: string @localized
  _: string @localized
  Type: string @localized
  _: rid
  _: rid
  Theme: ShopTag
  _: string
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: string
  _: bool
  _: bool
  _: bool
  _: string @localized
}