type QuestItems {
  BaseItemType: BaseItemTypes @unique
  TriggeredQuestFlag: QuestFlags
  UsedQuestFlag: QuestFlags
  _: i32
  _: [_] # All rows empty
  _: bool
  _: bool
  HelpText: ClientStrings
  Description: ClientStrings
  Script: string
  _: rid
  QuestFlag3: QuestFlags
  _: i32
  SellToNPCs: [NPCs]
  QuestFlag4: QuestFlags
}